### ISSUE TITLE
WebP Encoder Init Issue

### ISSUE THREAD

**Issue by Josh-McFarlin** [jamsinclair/jSquash#10]
In the [WebP encoder](https://github.com/jamsinclair/jSquash/blob/main/packages/jpeg/encode.ts) the following is used in the `init` functions to detect SIMD support:

```typescript
export async function init(module?: WebAssembly.Module): Promise<WebPModule> {
  if (await simd()) {
    const webpEncoder = await import('./codec/enc/webp_enc_simd');
    emscriptenModule = initEmscriptenModule(webpEncoder.default, module);
    return emscriptenModule;
  }
  const webpEncoder = await import('./codec/enc/webp_enc');
  emscriptenModule = initEmscriptenModule(webpEncoder.default, module);
  return emscriptenModule;
}
```

This causes the following error in Cloudflare workers since dynamic imports do not work:
```bash
TypeError: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at /Users/.../node_modules/@jsquash/webp/codec/enc/webp_enc_simd.js:9:8622
    ...
    at callRouteLoader (/Users/.../node_modules/@remix-run/server-runtime/esm/data.js:69:14) {
  input: 'webp_enc_simd.wasm',
  code: 'ERR_INVALID_URL'
}
```

It would be nice if the init function could be modified to something along the lines of:

```typescript
import webp_enc from './codec/dec/webp_enc';

export async function init(module?: WebAssembly.Module, simdModule?: WebAssembly.Module): Promise<WebPModule> {
  if (await simd()) {
    const webpEncoder = simdModule ? simdModule : await import('./codec/enc/webp_enc_simd');
    emscriptenModule = initEmscriptenModule(webpEncoder.default, module);
    return emscriptenModule;
  }

  emscriptenModule = initEmscriptenModule(webp_enc, module);
  return emscriptenModule;
}
```

This would allow the choice of opting-in/out of SIMD and support the Cloudflare environment by passing the SIMD module from the environment.

**Comment by Josh-McFarlin** [comment]
Actually after looking into this deeper, the issue is actually coming from this code within [webp_enc.js](https://github.com/jamsinclair/jSquash/blob/main/packages/webp/codec/enc/webp_enc.js):

```typescript
if (Module["locateFile"]) {
    var wasmBinaryFile = "webp_enc.wasm";
    if (!isDataURI(wasmBinaryFile)) {
        wasmBinaryFile = locateFile(wasmBinaryFile)
    }
} else {
    var wasmBinaryFile = new URL("webp_enc.wasm",
        import.meta.url).toString()
}
```

Surprisingly the same code is used within the encoder for JPEG, yet the JPEG encoder is able to be imported fine.

**Comment by Josh-McFarlin** [comment]
After review, I believe this issue is more to do with my environment than this library, so I will be closing this issue. Thanks!
